# Kitaru checkpoints for the deep research pipeline.
# Each function represents a discrete, recoverable step in the research process.
# Decorated with @checkpoint so Kitaru can save outputs and resume from failures.

import kitaru
from langchain.chat_models import init_chat_model
from kitaru import checkpoint

# LMStudio connection settings pulled from configuration.py
LMSTUDIO_BASE_URL = "http://192.168.1.79:8080/v1"
LMSTUDIO_API_KEY = "local"
MODEL = "openai:gpt-oss-120b"
SEARXNG_HOST = "http://192.168.1.36:4000"

def get_llm():
    """Return a configured LLM instance pointing to LMStudio."""
    return init_chat_model(
        model=MODEL,
        base_url=LMSTUDIO_BASE_URL,
        api_key=LMSTUDIO_API_KEY,
    )

# Replace with my checkpoint functions.
@checkpoint
def clarify_with_user(user_query: str) -> str:
    """Check if the query needs clarification before research begins.
    
    If the query is too vague or broad, pause and ask the human to clarify.
    If clear enough, return the query as-is and proceed.
    """
    from langchain_core.output_parsers import PydanticOutputParser
    from langchain_core.messages import HumanMessage
    from open_deep_library.prompts import clarify_with_user_instructions
    from open_deep_library.utils import get_today_str
    from open_deep_library.state import ClarifyWithUser

    llm = get_llm()
    parser = PydanticOutputParser(pydantic_object=ClarifyWithUser)

    prompt_content = clarify_with_user_instructions.format(
        messages=user_query,
        date=get_today_str(),
        format_instructions=parser.get_format_instructions()
    )

    raw_response = llm.invoke([HumanMessage(content=prompt_content)])
    response = parser.parse(raw_response.content)

    if response.need_clarification:
        # Pause the pipeline and ask the human to clarify
        clarified_query = kitaru.wait(
            name="clarify_query",
            question=response.question,
            schema=str,
            timeout=3600000000,
        )
        return clarified_query
    else:
        return user_query
    
# Writes the research brief given user query
@checkpoint
def write_research_brief(user_query: str) -> str:
    """Transform user messages into a structured research brief and initialize supervisor.
    
    This function analyzes the user's messages and generates a focused research brief
    that will guide the research supervisor. It also sets up the initial supervisor
    context with appropriate prompts and instructions.
    
    Args:
        user_query: The (clarified) user query.
        
    Returns:
        brief: The written research brief.
    """
     
    from langchain_core.output_parsers import PydanticOutputParser
    from langchain_core.messages import HumanMessage
    from open_deep_library.prompts import transform_messages_into_research_topic_prompt
    from open_deep_library.utils import get_today_str
    from open_deep_library.state import ResearchQuestion

    llm = get_llm()
    parser = PydanticOutputParser(pydantic_object=ResearchQuestion)

    # Generate structured research brief from user messages..
    prompt_content = transform_messages_into_research_topic_prompt.format(
        messages=user_query,
        date=get_today_str(),
        format_instructions=parser.get_format_instructions()
    )

    # Parse the response using PydanticOutputParser.
    raw_response = llm.invoke([HumanMessage(content=prompt_content)])
    response = parser.parse(raw_response.content)

    
    # No need to initialize the supervisor here, since Kitaru will pass off to the supervisor next.
    # We can just return the research brief here.
    return response.research_brief


# Breaks the plan into sub-tasks and delegates them.
# import the supervisor_subgraph from deep_researcher and re-use it.
@checkpoint
def run_research_supervisor(research_brief: str) -> list[str]:
    """Lead research supervisor that plans research strategy and delegates to researchers.
    
    The supervisor analyzes the research brief and decides how to break down the research
    into manageable tasks. It can use think_tool for strategic planning, ConductResearch
    to delegate tasks to sub-researchers, or ResearchComplete when satisfied with findings.
    
    Args:
        research_brief: str -- The research brief generated by write_research_brief above.
        
    Returns:
        notes: list[str] -- research notes collected by the researchers.
    """
    from deep_researcher import supervisor_subgraph
    from langchain_core.messages import SystemMessage, HumanMessage
    from open_deep_library.prompts import lead_researcher_prompt
    from open_deep_library.utils import get_today_str

    # Initialize the supervisor with research brief and instructions
    supervisor_system_prompt = lead_researcher_prompt.format(
        date=get_today_str(),
        max_concurrent_research_units=5,
        max_researcher_iterations=6
    )

    # The below comment will not disappear... Not sure why this is happening. Not a big deal.
    
    # Invoke the supervisor subgraph with the research brief
    result = supervisor_subgraph.invoke({
        "supervisor_messages": [
            SystemMessage(content=supervisor_system_prompt),
            HumanMessage(content=research_brief)
        ]
    })

    return result.get("notes", [])
    

# Collect the research from each researcher and compile into a finalized report.
@checkpoint
def final_report_generation(research_brief:str, notes: list[str]) -> str:
    """Generate the final comprehensive research report with retry logic for token limits.
    
    This function takes all collected research findings and synthesizes them into a 
    well-structured, comprehensive final report using the configured report generation model.
    
    Args:
        research_brief: The research brief generated by write_research_brief
        notes: Notes generated by the researchers in run_research_supervisor.
        
    Returns:
        The final report (just a string).
    """
    from langchain_core.messages import HumanMessage
    from open_deep_library.prompts import final_report_generation_prompt
    from open_deep_library.utils import get_today_str

    # Call get_llm because we are actually using the llm now.
    llm = get_llm()

    # Improved for robustness
    findings = "\n".join(str(n) for n in notes if n)

    # If want conversational memory, add the messages field as in.
    # If not, can scrap the messages field.
    final_report_prompt = final_report_generation_prompt.format(
                research_brief=research_brief,
                findings=findings,
                date=get_today_str()
            )

    # Invoke a response passing prompt to the LLM
    response = llm.invoke([HumanMessage(content=final_report_prompt)])

    # Return the response
    return response.content

# Saves the generated report as a markdown file.
@checkpoint
def save_report_markdown(final_report: str) -> str:
    """Saves the final report as a markdown file.
    
    Args:
        final_report: The final report generated by final_report_generation

    Returns:
        saved_report: The same final report. The function just saves the final report to the disk.
        We return the file just in case anything wrong happens in saving to the disk.
    """
    from datetime import datetime

    filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(final_report)
    
    print(f"Report saved to the disk")
    return final_report
